### ISSUE TITLE
H-1 Como usuaria quiero poder loguearme con mi usuario y contraseña para acceder al sitio web.

### ISSUE THREAD

**Issue by MayraMurillo** [MayraMurillo/LIM010-data-lovers#1]
Para completar en el primer sprint

**Comment by Gabby97** [comment]
Definición determinado:  Como equipo decidimos que para dar por terminado el primer sprint deberia estar testeado y subido al Github.

Criterios de aceptación: El usuario ingresa una contraseña y debe ser validada, de ser correcta debe dar pase a la siguiente página, de ser incorrecta debe saltar un mensaje de error.  Máximo 3 intentos, la página debe ser responsive.
